use std::error::Error;

use sqlx::{Connection, Row};

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let url = "postgres://PG_USER:PG_PASSWORD@HOST_NAME:5432/appdb";
    let mut conn = sqlx::postgres::PgConnection::connect(url).await?;

    let res = sqlx::query("select 1 + 1 as sum")
        .fetch_one(&mut conn)
        .await?;

    let sum: i32 = res.get("sum");
    println!("From Connection Value is [{sum}]");

    Ok(())
}
